/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Base tokens
        bg: "var(--bg)",
        surface: {
          DEFAULT: "#fff8f5",
          bright: "#fff8f5",
          dim: "#f5d3c0",
          low: "#fff1ea",
          container: "#ffeadf",
          high: "#ffe3d3",
          highest: "#fedcc8",
          lowest: "#ffffff",
          variant: "#fedcc8",
        },
        primary: {
          DEFAULT: "#6B3F1F",
          hover: "#4E2D12",
          container: "#50290b",
          fixed: "#ffdcc6",
          "fixed-dim": "#f8b990",
        },
        secondary: {
          DEFAULT: "#865227",
          container: "#feb783",
          fixed: "#ffdcc4",
          "fixed-dim": "#feb783",
        },
        tertiary: {
          DEFAULT: "#472f00",
          container: "#644400",
          fixed: "#ffdead",
          "fixed-dim": "#f4bd61",
        },
        "on-surface": "#29170c",
        "on-surface-variant": "#51443c",
        "on-primary": "#ffffff",
        "on-primary-container": "#eaac84",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#78461c",
        "outline-variant": "#d6c3b8",
        outline: "#84746b",
        "inverse-surface": "#402c1f",
        "inverse-primary": "#f8b990",
        text: {
          DEFAULT: "#2C1A0E",
          muted: "#8C7B6E",
        },
        border: "#E8DDD3",
        zalo: "#06C755",
        "accent-soft": "#F0E6DA",
        "accent-gold": "#C5A059",
      },
      fontFamily: {
        serif: ["var(--font-playfair)", "Playfair Display", "Georgia", "serif"],
        sans: ["var(--font-vietnam)", "Be Vietnam Pro", "sans-serif"],
        "headline-md": ["var(--font-playfair)", "Playfair Display", "Georgia", "serif"],
        "body-lg": ["var(--font-vietnam)", "Be Vietnam Pro", "sans-serif"],
        "title-editorial": ["var(--font-playfair)", "Playfair Display", "Georgia", "serif"],
        "headline-sm": ["var(--font-playfair)", "Playfair Display", "Georgia", "serif"],
        "label-meta": ["var(--font-vietnam)", "Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["var(--font-playfair)", "Playfair Display", "Georgia", "serif"],
        "display-hero": ["var(--font-playfair)", "Playfair Display", "Georgia", "serif"],
        "label-prominent": ["var(--font-vietnam)", "Be Vietnam Pro", "sans-serif"],
        "body-md": ["var(--font-vietnam)", "Be Vietnam Pro", "sans-serif"],
        "body-sm": ["var(--font-vietnam)", "Be Vietnam Pro", "sans-serif"],
        "label-pill": ["var(--font-vietnam)", "Be Vietnam Pro", "sans-serif"],
      },
      spacing: {
        "gutter-desktop": "2rem",
        "margin-desktop": "4rem",
        "space-4xl": "6rem",
        "gutter-mobile": "1rem",
        "space-xxs": "0.25rem",
        "space-2xl": "3rem",
        "margin-mobile": "1.25rem",
        "space-md": "1rem",
        "space-xl": "2rem",
        "space-sm": "0.75rem",
        "space-3xl": "4.5rem",
        "space-lg": "1.5rem",
        "space-xs": "0.5rem",
      },
      borderRadius: {
        card: "12px",
        btn: "8px",
        pill: "9999px",
      },
      boxShadow: {
        card: "0 2px 12px rgba(107,63,31,0.08)",
        sticky: "0 2px 8px rgba(107,63,31,0.12)",
      },
    },
  },
  plugins: [],
};
